### PR TITLE
Remove react element when template is destroyed

### LINKED ISSUE #76: React components never removed from DOM
Hi,

I'm probably doing something wrong, but I couldn't resist trying react-meteor out. I have added one page in my app which uses react-meteor for it's ui. It works just fine as I visit the page, but when I navigate away to another page the react component are not removed. If I then revisit the page a duplicate of the components is added etc. So how should I cleanup the DOM when navigating away?

Regards,
Herman

### PR DESCRIPTION
**Pull request by hmeerlo**
This fixes #76

### CODE REVIEW

**Comment by froatsnook** [comment]
Hey Herman,

Awesome that you fixed this.  Thank you!  I left a few comments on some stuff that doesn't belong in this pull request.  Maybe squash the commits and push a new version of this commit?  It will automatically update this pull request's commit.

I'm going to test it out now.  Hopefully this will get merged in ASAP.  Otherwise we will have to make a new package on atmosphere.  I can reproduce the issue like this:

```
{{#if case1}}
  {{> ReactComponent}}
{{/if}}
{{#if case2}}
  {{> OtherReactComponent}}
{{/if}}
```

As case1 and case2 switch between true and false, components are inserted and never removed.  I think it's super important that stuff like this works so that prospective meteor-react users can start to incorporate React into their code one component at a time.

@benjamn any ETA on a new release?  Or can you spread the commit bit for this project?  I (and 2.6k installs on atmosphere) think this react integration is really exciting!

**Comment by froatsnook** [comment]
OK so here's what I discovered:

Calling `React.unmountComponentAtNode(this.container);` only works if `renderInPlaceOfNode` didn't find any `prevSibs` or `nextSibs` (i.e. calling `container.insertBefore` or `container.appendChild` appears to be breaking `React.unmountComponentAtNode`).  You can check this by looking at the return value of `React.unmountComponentAtNode`.  I put breakpoints in `renderInPlaceOfNode` to test this.

The work-around is to wrap all rendered components in containers that don't have any other children.

```html
<!-- WRONG -->
<div class="container">
{{> ReactComponent1}}
<p>Now that .container has two children, React.unmountComponentAtNode will fail</p>
</div>

<!-- OK -->
<div class="container">
<div>{{> ReactComponent1}}</div>
<p>Now that ReactComponent has its own container, everything is OK</p>
</div>
```

Note: even a text node will break the unmounting:

```html
<!-- ALSO WRONG -->
<div class="container">
{{> ReactComponent1}}


</div>
```

So the next question is how react-meteor should handle this.  From what I can tell, at the moment a placeholder span is replaced by the newly rendered component (btw, this seems like a hack... what if there's another span in the container?).  Maybe we should use a div instead of a span and render inside that div instead of inside the container?  It might piss off some users that their markup doesn't look as they'd expect (with an extra div inserted), but it would probably piss them off less than not removing elements would.

**Comment by hmeerlo** [comment]
Thanx for your research. I will take a look at it!

**Comment by hmeerlo** [comment]
I can not reproduce what you are saying. It works fine for me in the mentioned cases above. Can you step into the unmount call to see why it fails?

**Comment by froatsnook** [comment]
@hmeerlo Here you can reproduce: https://github.com/froatsnook/meteor-react-multi-render

Click each button a bunch of times.  The react components Component1 and Component2 will be repeatedly added and never removed (even with your patch).

**Comment by hmeerlo** [comment]
Ok, found out what the problem is and why it worked for me and not in your reproduction scenario. React requires the first child of the parent node to have a reactid. But in your case the first child is a button without a reactid so it fails. It worked for me because I only appended (insertAfter) nodes to the parent. The comment above renderInPlaceOfNode basically says it all:

```
// Like React.render, but it replaces targetNode, and works even if
// targetNode.parentNode has children other than targetNode.
```

The tricky part is in the 'even if targetNode.parentNode has children other than targetNode'. react-meteor tries to do something react can not do and therefore the behaviour afterwards is different. I think you should just not support any other nodes in the parentNode besides the react component. But that's just my 2 cents.

**Comment by froatsnook** [comment]
@hmeerlo I still don't quite get it.  This doesn't work (even though the first child has a reactid):

```html
  <div class="container">
    {{#if test2}}
      {{> Component2 }}
      {{> Component2 }}
    {{/if}}
  </div>
```

and this appears to work (i.e. components get added and removed properly), although componentWillUnmount doesn't seem to be called:

```html
  {{#if test2}}
    <div class="container">
      {{> Component2 }}
      {{> Component2 }}
    </div>
  {{/if}}
```

For now I'm going to just always put containers around my react components.  But do you have any ideas on how to make the library "safe"?

**Comment by hmeerlo** [comment]
@froatsnook It is actually clear to me (and hopefully to you as well after this :-) ). The first case you mention doesn't work because the first child of the container is a text node with a carriage return and no reactid. So the react component is not removed. And in the second case the entire container is removed by Blaze instead of React because of the #if statement around the container.

I think to make the library safe we should not support the siblings in the renderInPlaceOfNode call. So only append the react component and remove the siblings and document it properly.

**Comment by froatsnook** [comment]
Ha, I forgot the text node!  Thanks for catching that.

Unfortunate conclusion, but it makes sense.  Maybe it makes sense to print a warning message if `process.env.NODE_ENV === "development"` or something and there's more than a whitespace text node that gets removed :), and then print a suggestion to wrap it with a container.

**Comment by hmeerlo** [comment]
I will extend my fix with this and squash the commits.

**Comment by hmeerlo** [comment]
I think your solution makes it too complex, I updated my code to reflect how I think it should have been. Just use the exact same behavior as React so the integration is much cleaner. Don't try to support the siblings because it will probably break in the future when something in react changes.

**Comment by benjamn** [comment]
Thanks for offering your opinion, @hmeerlo. I consider it a significant failing of `React.render` and `React.unmountComponentAtNode` that they aren't designed to handle siblings, so I hope you'll forgive me for working around those shortcomings in a way that works for now. If it breaks in the future, I'll find a different way to work around it.

**Pull request closed without merging**
